//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seaFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        [DisplayName("Giá"), DisplayFormat(DataFormatString = "{0:0,0}", ApplyFormatInEditMode = true)]
        public Nullable<int> price { get; set; }
        public string images { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> subcategory_id { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual subcategory subcategory { get; set; }
    }
}
